apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: eiatmiyuw-python 
  janus-idp.io/tekton: eiatmiyuw-python
  backstage.io/kubernetes-id: eiatmiyuw-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: eiatmiyuw-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml